# Generated by Django 2.2.5 on 2019-10-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0003_auto_20191009_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoidung',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
