# Generated by Django 2.2.1 on 2019-06-04 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='nguoi_dung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='to_do_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_create', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.nguoi_dung')),
            ],
        ),
        migrations.CreateModel(
            name='to_do_share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_do', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todoshare_todo', to='todolist.to_do_list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todoshare_user', to='todolist.nguoi_dung')),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('to_do', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.to_do_list')),
            ],
        ),
    ]
