# Generated by Django 2.2.2 on 2019-06-05 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='to_do',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todoitem', to='todolist.to_do_list'),
        ),
    ]
